# Generated by Django 4.2.27 on 2026-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True),
        ),
    ]
