# Generated by Django 4.2.27 on 2026-01-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_payment_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prepared_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signed_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
