# Generated by Django 4.2.27 on 2026-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='vat_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
