# Generated by Django 4.2.27 on 2026-01-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_invoiceitem_vat_exempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="stock_deducted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
