# Generated by Django 4.2.27 on 2026-01-05 16:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoiceitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
