# Generated by Django 4.2.27 on 2026-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category_other",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Other (specify)"),
        ),
    ]
