# Generated by Django 4.2.27 on 2026-01-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('managing_director', 'Managing Director'), ('manager', 'Manager'), ('sales', 'Sales Staff'), ('store', 'Store Manager'), ('accountant', 'Accountant')], default='sales', max_length=20),
        ),
    ]
