# Generated by Django 4.2.27 on 2026-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productsequence_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
