# Generated by Django 4.2.27 on 2026-01-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_vat_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='supplierproductprice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_prices', to='inventory.product'),
        ),
    ]
