# Generated by Django 4.2.27 on 2026-01-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplierproductprice_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
