# Generated by Django 4.2.27 on 2026-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_supplierproductprice_lead_time_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproductprice',
            name='min_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierproductprice',
            name='quantity_unit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
