# Generated by Django 4.2.27 on 2026-01-04

from django.db import migrations


DEFAULT_CATEGORIES = [
    ("IT PRODUCTS", "itproduct"),
    ("PRINTING MATERIAL", "printing_material"),
    ("BRANDING MATERIAL", "branding_material"),
    ("PROMOTIONAL MATERIAL", "promotional_material"),
    ("MACHINERY", "machinery"),
    ("STATIONERY", "stationery"),
    ("PPE", "ppe"),
    ("GENERAL", "general"),
    ("OTHER", "other"),
]


OLD_TYPE_TO_NEW_TYPE = {
    "it": "itproduct",
    "printing": "printing_material",
    "medical": "general",
    "ppe": "ppe",
}


def seed_and_migrate_categories(apps, schema_editor):
    ProductCategory = apps.get_model("inventory", "ProductCategory")

    # Migrate any legacy category_type values to the new taxonomy.
    for old_type, new_type in OLD_TYPE_TO_NEW_TYPE.items():
        ProductCategory.objects.filter(category_type=old_type).update(category_type=new_type)

    # Ensure the required categories exist (used by /inventory/add/ dropdown).
    for name, category_type in DEFAULT_CATEGORIES:
        obj, created = ProductCategory.objects.get_or_create(
            name=name,
            defaults={"category_type": category_type},
        )
        if not created and getattr(obj, "category_type", None) != category_type:
            ProductCategory.objects.filter(pk=obj.pk).update(category_type=category_type)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_alter_product_low_stock_threshold_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_and_migrate_categories, migrations.RunPython.noop),
    ]
