# Generated by Django 4.2.27 on 2026-01-05 16:16

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auditevent'),
        ('invoices', '0010_invoiceitem_unit_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='UGX', max_length=10)),
                ('product_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('product_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('product_profit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('service_sales_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('service_cost_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('service_profit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_record', to='invoices.invoice')),
                ('trigger_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_records', to='invoices.payment')),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
                'indexes': [models.Index(fields=['branch', '-recorded_at'], name='reports_pro_branch__6331e4_idx')],
            },
        ),
    ]
