# Generated by Django 4.2.27 on 2026-01-02 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
        ('sales', '0003_rename_quotation_vat_amount'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='related_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='bids.bid'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.quotation'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('quotation', 'Quotation'), ('proforma', 'Proforma'), ('receipt', 'Receipt'), ('tender', 'Tender Document'), ('compliance', 'Compliance File'), ('contract', 'Contract'), ('id', 'ID'), ('other', 'Other')], max_length=20),
        ),
    ]
