# Generated by Django 4.2.27 on 2026-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_related_bid_document_related_quotation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="doc_type_other",
            field=models.CharField(blank=True, default="", max_length=120, verbose_name="Other (specify)"),
        ),
    ]
