# Generated by Django 4.2.27 on 2026-01-08 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0005_backfill_document_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Approval Notes'),
        ),
        migrations.AddField(
            model_name='document',
            name='approval_workflow',
            field=models.CharField(choices=[('none', 'No Approval Required'), ('single', 'Single Approver'), ('multi', 'Multiple Approvers'), ('sequential', 'Sequential Approval')], default='none', max_length=20, verbose_name='Approval Workflow'),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='document',
            name='approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Digitally Signed'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Is Template'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='document',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_documents', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By'),
        ),
        migrations.AddField(
            model_name='document',
            name='requires_signature',
            field=models.BooleanField(default=False, verbose_name='Requires Digital Signature'),
        ),
        migrations.AddField(
            model_name='document',
            name='signature_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Signature Data'),
        ),
        migrations.AddField(
            model_name='document',
            name='template_fields',
            field=models.JSONField(blank=True, null=True, verbose_name='Template Fields'),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Verification Status'),
        ),
    ]
