# Generated by Django 4.2.27 on 2026-01-02 00:30

from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bids", "0001_initial"),
        ("clients", "0001_initial"),
        ("sales", "0003_rename_quotation_vat_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="submission_deadline",
            new_name="closing_date",
        ),
        migrations.AddField(
            model_name="bid",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bids",
                to="sales.quotation",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_bids",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="tender_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="bid",
            name="outcome",
            field=models.CharField(
                choices=[("pending", "Pending"), ("won", "Won"), ("lost", "Lost")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="required_documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bids/required/",
                validators=[FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="compliance_notes",
            field=models.TextField(blank=True),
        ),
    ]
