# Generated by Django 4.2.27 on 2026-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_submission_method_and_status_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='outcome',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
