# Generated by Django 4.2.27 on 2026-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		("appointments", "0002_appointment_reminder_sent_at"),
	]

	operations = [
		migrations.AddField(
			model_name="appointment",
			name="meeting_mode",
			field=models.CharField(
				choices=[("physical", "Physical"), ("google_meet", "Google Meet"), ("whatsapp", "WhatsApp")],
				default="physical",
				max_length=20,
			),
		),
		migrations.AddField(
			model_name="appointment",
			name="meeting_location",
			field=models.CharField(blank=True, max_length=255),
		),
		migrations.AddField(
			model_name="appointment",
			name="meeting_link",
			field=models.URLField(blank=True),
		),
		migrations.AddField(
			model_name="appointment",
			name="meeting_phone",
			field=models.CharField(blank=True, max_length=50),
		),
	]
