# Generated by Django 4.2.27 on 2026-01-02 00:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='category',
            field=models.CharField(choices=[('printing', 'Printing'), ('branding', 'Branding'), ('it', 'IT'), ('medical', 'Medical'), ('ppe', 'PPE'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
