# Generated by GitHub Copilot on 2026-01-02

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [
		("sales", "0002_quotation_category_quotation_discount_amount_and_more"),
	]

	operations = [
		migrations.RenameField(
			model_name="quotation",
			old_name="vat_amount",
			new_name="vat_amount_amount",
		),
	]
