# Generated by Django 4.2.27 on 2026-01-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quotation_category_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='vat_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
