# Generated by Django 4.2.27 on 2026-01-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quotationitem_vat_exempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='category',
            field=models.CharField(choices=[('printing', 'Printing'), ('branding', 'Branding'), ('it', 'IT'), ('medical', 'Medical'), ('ppe', 'PPE'), ('general_supplies', 'General Supplies'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
