# Generated by Django 4.2.27 on 2026-01-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('sales', '0006_alter_quotation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service'),
        ),
    ]
