# Generated by Django 4.2.27 on 2026-01-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_quotation_cancellation_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
